# Generated by Django 5.2 on 2025-04-29 16:39

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_openhouse_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='lead_images/'),
        ),
        migrations.AlterField(
            model_name='openhouse',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='propertyvisit',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='visit_images/'),
        ),
        migrations.AlterField(
            model_name='propertyvisit',
            name='visit_date',
            field=models.DateTimeField(),
        ),
    ]
